const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info : {
        title: 'Documentation Autogenerated',
        description : 'Documentation Autogeneré par swagger',
        version : '1.0'
    },
    host: 'localhost:5000',
};

const outputFile = './swagger-output.json';
const routes = ['./app.js'];

swaggerAutogen(outputFile, routes, doc)